CC= gcc
CFLAGS= -Werror -Wextra -Wall -pedantic -std=c99 -g

SRC= src/main.c src/help/help.c src/parse/parse.c src/makefile/makefile.c src/execution/execution.c
BIN= minimake2

all: minimake2

minimake2:
	$(CC) $(CFLAGS) -o $(BIN) $(SRC)

clean:
	rm $(BIN)
